name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: json
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Foresight Test Report Uploader
        uses: actions/upload-artifact@v2
        with:
          name: test-result-jest
          path: ./target
      - name: Run TIA tests
        run: "npm run test:tia -- '${{ steps.files.outputs.all }}'"
        if: ${{ contains(join(steps.files.outputs.all), 'src/')}}
